-- MySQL Script generated by MySQL Workbench
-- Thu Nov  5 00:00:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`progress_skripsi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`progress_skripsi` (
  `id_skripsi_proses` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  `tanggal_pengajuan` DATE NULL,
  `id_dosen_int` VARCHAR(45) NULL,
  `id_kajur` INT NULL,
  `id_mahasiswa` INT NULL,
  `id_admin` INT NULL,
  PRIMARY KEY (`id_skripsi_proses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`skripsi_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`skripsi_personal` (
  `id_skripsi` INT NOT NULL,
  `judul` VARCHAR(45) NULL,
  `file` VARCHAR(45) NULL,
  `tema` VARCHAR(45) NULL,
  `id_admin` VARCHAR(45) NULL,
  `id_mahasiswa` INT NULL,
  `skripsi_personalcol` INT NULL,
  PRIMARY KEY (`id_skripsi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`log_skripsi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`log_skripsi` (
  `id_log_skripsi` INT NOT NULL,
  `topic` VARCHAR(45) NULL,
  `comment_mhs` VARCHAR(45) NULL,
  `comment_dosen` VARCHAR(45) NULL,
  `file` VARCHAR(45) NULL,
  `id_dosen` INT NULL,
  `id_mahasiswa` INT NULL,
  PRIMARY KEY (`id_log_skripsi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`user` (
  `id_user` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `kontak` VARCHAR(45) NULL,
  `nama` VARCHAR(45) NULL,
  `id_identitas` VARCHAR(45) NULL,
  `credential` INT NULL,
  `id_skripsi` INT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_identitas_UNIQUE` (`id_identitas` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
